development:
  adapter: mysql2
  database: combzhackpostal_dev
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  database: combzhackpostal_test
  host: localhost
  username: root
  password:
