# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d53d8327e747770b43b11cde5dcaac7638b564a1ec5d5aebab7f65f7a2280ffb6a87fde6f8690cd418c119c3fa6c258174859fd3b201200947d70ca643ffee

test:
  secret_key_base: a42a6da159253c330ea4305bfe40993577fcc608c9a2db9edb11d2ce9767464694547efcab96e7a09ad491951d861dc4fa0b44a9f1f52bf821cd0f73da1b3648

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
